version: '3.8'

services:
  database:
    image: mysql:8.0
    container_name: my_database
    environment:
      MYSQL_ROOT_PASSWORD: yara2001
      MYSQL_DATABASE: payment_system
      MYSQL_USER: aliyara
      MYSQL_PASSWORD: yara2001
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: myapp-phpmyadmin
    restart: always
    environment:
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: yara2001
    ports:
      - "8080:80"

volumes:
  db_data:
